# Generated by Django 5.0.7 on 2024-10-31 05:55

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(unique=True, validators=[accounts.validators.validate_phone]),
        ),
    ]
